### ISSUE TITLE
# symbol in string causes issues with subsequent parameters

### ISSUE THREAD

**Issue by NRJank** [gnu-octave/SavannahAPI#2]
wanted to do a query with a keyword search for "file #"  (so Keywords=file%20%# )

having the # at the end of the string causes it to ignore all subsequent lines.

e.g., the following works:

```
Action=get
Limit=10
Format=HTMLCSS
Keywords=file%20#
```

but 
```
Action=get
Keywords=file%20#
Limit=10
Format=HTMLCSS
```

ignores the Limit and Format parameters.

**Comment by siko1056** [comment]
Thank you for the report @NRJank I'll take a look at it :wink:

**Comment by siko1056** [comment]
With the previous changeset the situation might have improved.  If not, please give another failing example here :wink:

**Comment by NRJank** [comment]
> With the previous changeset the situation might have improved. If not, please give another failing example here 😉

seems fixed based on a few attempts to recreate the issues or something similar.
