### ISSUE TITLE
Recent changes are shown as SubmittedOn "> 52 year(s) ago"

### ISSUE THREAD

**Issue by mmuetzel** [gnu-octave/SavannahAPI#4]
I'm not sure if this is only a local issue.
With Edge on Windows 11, the page shows this for me currently:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/65065102/177144991-28615d71-31e7-44f0-8a68-fa37c047262f.png">

**Comment by siko1056** [comment]
Thanks for the catch @mmuetzel .

The fate of web scraping software.  Unfortunately, this small change results in a larger issue.  The whole database has to be scraped again, probably on the weekend :sweat: 

https://github.com/gnu-octave/savane/commit/ed4179d6c21b1551b514b5a92b833d7fb1f10c1c

**Comment by siko1056** [comment]
Again thanks for mentioning it @mmuetzel and sorry for the delay and down time.  I re-read the whole bug index and the scraping took about 3 hours.  Now things should update automatically again.
